-- Friendly bike-model names for Harley model codes (FLHR -> "Road King").
-- Used only to tag the model codes in the catalog UI. Best-effort seed — edit
-- freely; a code with no row here just shows the raw code.
--
-- Additive & safe to re-run (INSERT ... ON CONFLICT DO NOTHING keeps your edits).

create table if not exists model_name (
  model_code   text primary key,
  name         text not null,
  model_family text
);

insert into model_name (model_code, name, model_family) values
  -- Touring
  ('FLHR',     'Road King',                       'Touring'),
  ('FLHR/I',   'Road King (EFI)',                 'Touring'),
  ('FLHRI',    'Road King (EFI)',                 'Touring'),
  ('FLHRCI',   'Road King Classic (EFI)',         'Touring'),
  ('FLHS',     'Electra Glide Sport',             'Touring'),
  ('FLHT',     'Electra Glide Standard',          'Touring'),
  ('FLHT/I',   'Electra Glide Standard (EFI)',    'Touring'),
  ('FLHTC',    'Electra Glide Classic',           'Touring'),
  ('FLHTC/I',  'Electra Glide Classic (EFI)',     'Touring'),
  ('FLHTCI',   'Electra Glide Classic (EFI)',     'Touring'),
  ('FLHTCU',   'Ultra Classic Electra Glide',     'Touring'),
  ('FLHTCU/I', 'Ultra Classic Electra Glide (EFI)','Touring'),
  ('FLHTCUI',  'Ultra Classic Electra Glide (EFI)','Touring'),
  ('FLTC',     'Tour Glide Classic',              'Touring'),
  ('FLTC/FLHTC','Tour Glide / Electra Glide Classic','Touring'),
  ('FLTCU',    'Ultra Classic Tour Glide',        'Touring'),
  ('FLTCUI',   'Ultra Classic Tour Glide (EFI)',  'Touring'),
  ('FLTR',     'Road Glide',                      'Touring'),
  ('FLTR/I',   'Road Glide (EFI)',                'Touring'),
  ('FLTRI',    'Road Glide (EFI)',                'Touring'),
  -- Softail
  ('FLDE',     'Deluxe',                          'Softail'),
  ('FLFB',     'Fat Boy',                         'Softail'),
  ('FLFBS',    'Fat Boy S',                       'Softail'),
  ('FLFBSANV', 'Fat Boy Anniversary',             'Softail'),
  ('FLHC',     'Heritage Classic',                'Softail'),
  ('FLHCS',    'Heritage Classic (114)',          'Softail'),
  ('FLHCSANV', 'Heritage Classic Anniversary',    'Softail'),
  ('FLI',      'Hydra Glide Revival',             'Softail'),
  ('FLS',      'Softail Slim',                    'Softail'),
  ('FLSB',     'Sport Glide',                     'Softail'),
  ('FLSL',     'Softail Slim',                    'Softail'),
  ('FLSS',     'Slim S',                          'Softail'),
  ('FLST',     'Heritage Softail',                'Softail'),
  ('FLSTC',    'Heritage Softail Classic',        'Softail'),
  ('FLSTCI',   'Heritage Softail Classic (EFI)',  'Softail'),
  ('FLSTF',    'Fat Boy',                         'Softail'),
  ('FLSTFI',   'Fat Boy (EFI)',                   'Softail'),
  ('FLSTFB',   'Fat Boy Lo',                      'Softail'),
  ('FLSTFBS',  'Fat Boy S',                       'Softail'),
  ('FLSTI',    'Heritage Softail (EFI)',          'Softail'),
  ('FLSTN',    'Softail Deluxe',                  'Softail'),
  ('FLSTNI',   'Softail Deluxe (EFI)',            'Softail'),
  ('FLSTS',    'Heritage Springer',               'Softail'),
  ('FLSTSB',   'Cross Bones',                     'Softail'),
  ('FLSTSC',   'Softail Springer Classic',        'Softail'),
  ('FLSTSCI',  'Softail Springer Classic (EFI)',  'Softail'),
  ('FLSTSI',   'Heritage Springer (EFI)',         'Softail'),
  ('FXBB',     'Street Bob',                      'Softail'),
  ('FXBBS',    'Street Bob 114',                  'Softail'),
  ('FXBR',     'Breakout',                        'Softail'),
  ('FXBRS',    'Breakout S',                      'Softail'),
  ('FXCW',     'Rocker',                          'Softail'),
  ('FXCWC',    'Rocker C',                        'Softail'),
  ('FXFB',     'Fat Bob',                         'Softail'),
  ('FXFBS',    'Fat Bob 114',                     'Softail'),
  ('FXLR',     'Low Rider',                       'Softail'),
  ('FXLRS',    'Low Rider S',                     'Softail'),
  ('FXLRST',   'Low Rider ST',                    'Softail'),
  ('FXRST',    'Low Rider ST',                    'Softail'),
  ('FXS',      'Blackline',                       'Softail'),
  ('FXSB',     'Breakout',                        'Softail'),
  ('FXST',     'Softail Standard',                'Softail'),
  ('FXSTI',    'Softail Standard (EFI)',          'Softail'),
  ('FXSTB',    'Night Train',                     'Softail'),
  ('FXSTBI',   'Night Train (EFI)',               'Softail'),
  ('FXSTC',    'Softail Custom',                  'Softail'),
  ('FXSTD',    'Softail Deuce',                   'Softail'),
  ('FXSTDI',   'Softail Deuce (EFI)',             'Softail'),
  ('FXSTS',    'Springer Softail',                'Softail'),
  ('FXSTSI',   'Springer Softail (EFI)',          'Softail'),
  ('FXSTSB',   'Bad Boy',                         'Softail')
on conflict (model_code) do nothing;
